#!/bin/bash
# ============================================
# سكريبت نشر تطبيق شركة العزب للمقاولات
# Alazab Construction App - Auto Deploy Script
# ============================================

set -e  # Stop on any error

# ─── Configuration ───
APP_NAME="alazab.com"
DOMAIN="alazab.com"
DEPLOY_DIR="/var/www/alazab.com"
REPO_URL="https://github.com/AlazabDev/alazab.com"
BRANCH="main"
SUPABASE_URL="https://bxuhcbfdoaflsgbxiqei.supabase.co"
SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4dWhjYmZkb2FmbHNnYnhpcWVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwMTU1MDIsImV4cCI6MjA4NDU5MTUwMn0.W60YuL2zn9De95Jwgc7jn4_NLMdOVINHO6NUWY6yRlQ"
SUPABASE_PUBLISHABLE_DEFAULT_KEY="sb_publishable_0WP0CHLPKhJ7mx1jMmnaYg_vl5zlrCR"
SUPABASE_ID="bxuhcbfdoaflsgbxiqei"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
error() { echo -e "${RED}[✗]${NC} $1"; exit 1; }
info() { echo -e "${BLUE}[i]${NC} $1"; }

echo ""
echo "=========================================="
echo "  شركة العزب للمقاولات العامة"
echo "  Alazab Construction - Auto Deploy"
echo "=========================================="
echo ""

# ─── Step 1: Check prerequisites ───
info "فحص المتطلبات..."

command -v node >/dev/null 2>&1 || error "Node.js غير مثبت. ثبته أولاً: https://nodejs.org"
command -v npm >/dev/null 2>&1 || error "npm غير مثبت"
command -v nginx >/dev/null 2>&1 || warn "Nginx غير مثبت - سيتم تخطي إعداد الخادم"

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
  error "يتطلب Node.js 18 أو أحدث. الإصدار الحالي: $(node -v)"
fi

log "المتطلبات متوفرة (Node $(node -v))"

# ─── Step 2: Clone or pull repo ───
info "تحديث الكود المصدري..."

if [ -z "$REPO_URL" ]; then
  warn "لم يتم تحديد REPO_URL - يتم استخدام المجلد الحالي"
  PROJECT_DIR="."
else
  PROJECT_DIR="/tmp/${APP_NAME}-build"
  if [ -d "$PROJECT_DIR" ]; then
    cd "$PROJECT_DIR"
    git fetch origin
    git reset --hard "origin/${BRANCH}"
    log "تم تحديث الكود"
  else
    git clone --branch "$BRANCH" --depth 1 "$REPO_URL" "$PROJECT_DIR"
    cd "$PROJECT_DIR"
    log "تم استنساخ الكود"
  fi
fi

cd "$PROJECT_DIR"

# ─── Step 3: Install dependencies ───
info "تثبيت الحزم..."
npm ci --production=false --silent 2>/dev/null || npm install --silent
log "تم تثبيت الحزم"

# ─── Step 4: Create .env file ───
info "إعداد متغيرات البيئة..."

cat > .env.production << EOF
VITE_SUPABASE_URL=${SUPABASE_URL}
VITE_SUPABASE_PUBLISHABLE_KEY=${SUPABASE_ANON_KEY}
VITE_SUPABASE_PROJECT_ID=
EOF

log "تم إنشاء ملف البيئة"

# ─── Step 5: Build ───
info "بناء التطبيق للإنتاج..."
pnpm build
log "تم بناء التطبيق بنجاح"

# ─── Step 6: Deploy ───
info "نشر الملفات..."

sudo mkdir -p "$DEPLOY_DIR"
sudo rm -rf "${DEPLOY_DIR:?}/"*
sudo cp -r dist/* "$DEPLOY_DIR/"
sudo chown -R www-data:www-data "$DEPLOY_DIR"
sudo chmod -R 755 "$DEPLOY_DIR"

log "تم نشر الملفات إلى ${DEPLOY_DIR}"

# ─── Step 7: Configure Nginx ───
if command -v nginx >/dev/null 2>&1; then
  info "إعداد Nginx..."
  
  NGINX_CONF="/etc/nginx/sites-available/${APP_NAME}"

  sudo tee "$NGINX_CONF" > /dev/null << NGINX_EOF
# Alazab Construction App - Nginx Config
# Generated by deploy script

# HTTP → HTTPS redirect
server {
    listen 80;
    server_name ${DOMAIN} www.${DOMAIN};
    return 301 https://\$host\$request_uri;
}

# Main HTTPS server
server {
    listen 443 ssl http2;
    server_name ${DOMAIN} www.${DOMAIN};

    root ${DEPLOY_DIR};
    index index.html;

    # SSL (managed by certbot)
    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://connect.facebook.net https://graph.facebook.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https:; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://graph.facebook.com https://connect.facebook.net; frame-src https://www.facebook.com https://web.facebook.com;" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript image/svg+xml;

    # Static assets caching
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|webp)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files \$uri =404;
    }

    # SPA routing
    location / {
        try_files \$uri \$uri/ /index.html;
    }

    # Proxy Edge Functions through your domain
    location /functions/v1/ {
        proxy_pass https://zrrffsjbfkphridqyais.supabase.co/functions/v1/;
        proxy_set_header Host zrrffsjbfkphridqyais.supabase.co;
        proxy_ssl_server_name on;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 60s;
    }

    # Block sensitive files
    location ~ /\. {
        deny all;
    }

    # Error pages
    error_page 404 /index.html;
}
NGINX_EOF

  # Enable site
  sudo ln -sf "$NGINX_CONF" "/etc/nginx/sites-enabled/${APP_NAME}"

  # Test and reload
  sudo nginx -t && sudo systemctl reload nginx
  log "تم إعداد Nginx"
else
  warn "Nginx غير مثبت - تخطي إعداد الخادم"
fi

# ─── Step 8: SSL Certificate ───
if command -v certbot >/dev/null 2>&1; then
  if [ ! -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ]; then
    info "إعداد شهادة SSL..."
    sudo certbot --nginx -d "$DOMAIN" -d "www.${DOMAIN}" --non-interactive --agree-tos --email admin@${DOMAIN}
    log "تم إعداد SSL"
  else
    log "شهادة SSL موجودة مسبقاً"
  fi
else
  warn "Certbot غير مثبت. لتثبيته: sudo apt install certbot python3-certbot-nginx"
fi

# ─── Step 9: Cleanup ───
if [ "$PROJECT_DIR" != "." ] && [ -d "$PROJECT_DIR" ]; then
  rm -rf "$PROJECT_DIR"
fi

# ─── Done ───
echo ""
echo "=========================================="
echo -e "  ${GREEN}✓ تم النشر بنجاح!${NC}"
echo "=========================================="
echo ""
echo "  🌐 الموقع: https://${DOMAIN}"
echo "  📁 المسار: ${DEPLOY_DIR}"
echo "  🔗 Webhook: https://${DOMAIN}/functions/v1/whatsapp-webhook"
echo ""
echo "  للتحديث المستقبلي، شغل هذا السكريبت مرة أخرى:"
echo "  bash deploy.sh"
echo ""
