export const SITE_SETTINGS = {
  brand: {
    nameAr: "شركة العزب للمقاولات وإدارة التنفيذ",
    nameEn: "Alazab Construction Company",
    sloganAr: "هندسة وتنفيذ بمعايير عالية",
    sloganEn: "Engineering & Execution Excellence",
    primaryColor: "#f5bf23",
    secondaryColor: "#ffb900",
    logoLight: "https://al-azab.co/w.png",
    logoDark: "https://al-azab.co/b.png",
  },
  contact: {
    addressAr: "شارع المعادي 500/8، القاهرة، مصر",
    addressEn: "8/500 Maadi Street, Cairo, Egypt",
    phonePrimary: "+20 100 400 6620",
    phoneSecondary: "+20 101 453 6600",
    email: "info@al-azab.co",
    workingHoursAr: "السبت - الخميس: 9 صباحاً - 6 مساءً",
    workingHoursEn: "Saturday - Thursday: 9:00 AM - 6:00 PM",
  },
  hero: {
    titleAr: "نحول الرؤية إلى مشاريع معمارية متقنة",
    titleEn: "Turning Vision into High-Standard Architecture",
    subtitleAr: "تصميم، إدارة تنفيذ، وتشغيل بإدارة احترافية",
    subtitleEn: "Design, execution management, and operations with precision",
    ctaPrimaryAr: "احصل على استشارة",
    ctaPrimaryEn: "Request Consultation",
    ctaSecondaryAr: "مشاريعنا",
    ctaSecondaryEn: "View Projects",
  },
  services: [
    {
      key: "architectural",
      titleAr: "التصميم المعماري",
      titleEn: "Architectural Design",
      summaryAr: "مخططات تنفيذية وتصورات هندسية متكاملة.",
      summaryEn: "Execution-ready plans and integrated architectural studies.",
    },
    {
      key: "interior",
      titleAr: "التصميم الداخلي",
      titleEn: "Interior Design",
      summaryAr: "حلول تصميمية تعكس هوية العميل وتضمن الراحة.",
      summaryEn: "Design solutions that reflect client identity and comfort.",
    },
    {
      key: "management",
      titleAr: "إدارة المشاريع",
      titleEn: "Project Management",
      summaryAr: "جدولة دقيقة ومتابعة جودة ومخاطر فعالة.",
      summaryEn: "Precise scheduling with quality and risk oversight.",
    },
    {
      key: "maintenance",
      titleAr: "الصيانة وإدارة المرافق",
      titleEn: "Maintenance & Facilities",
      summaryAr: "خطط تشغيل وصيانة تضمن استمرارية الأداء.",
      summaryEn: "Operations and maintenance plans that sustain performance.",
    },
  ],
  seo: {
    siteUrl: "https://al-azab.co",
    ogImage: "/og-alazab.svg",
  },
}
